name: verifyme
description: "A simple TOTP Authenticator app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: 
  get: 
  get_storage:
  path_provider:
  otp:
  base32:
  cupertino_icons: 
  barcode_scan2:
    git:
      url: https://github.com/mdddj/barcode_scan2
  permission_handler:
  file_picker:
  flutter_i18n:
  flutter_colorpicker: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 


flutter:

  uses-material-design: true

  assets:
    - assets/locales/