name: Build Flutter APK & IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ios --no-codesign

      - name: Archive IPA
        run: |
          mkdir -p build/ios/archive
          cd build/ios/archive
          zip -r app-release.ipa ../iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/archive/app-release.ipa
