name: Build Flutter APK & IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.0
        with:
          name: VerifyMe-Android
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Code Signing)
        run: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/ios
          cd build/ios/Build/Products/Release-iphoneos
          xcrun bitcode_strip Runner.app/Frameworks/Flutter.framework/Flutter -r -o Runner.app/Frameworks/Flutter.framework/Flutter
          mkdir Payload
          mv Runner.app Payload/
          zip -r9 app.ipa Payload

      - name: Rename IPA
        run: |
          version_name=$(yq e .version pubspec.yaml | cut -d "+" -f 1)
          for file in app.ipa; do
            new_file_name="build/VerifyMe-${version_name}.ipa"
            mv "$file" "$new_file_name"
          done

      - name: Upload IPA
        uses: actions/upload-artifact@v4.6.0
        with:
          name: VerifyMe-iOS
          path: build/VerifyMe-*.ipa
