name: Build Flutter APK & IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.0
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Code Signing)
        run: flutter build ios --no-codesign

      - name: Archive iOS app
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/output

      - name: Upload IPA
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ios-ipa
          path: build/ios/output/*.ipa
